### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by ducquandls** [ZitongYu/PhysFormer#10]
hello, I run inference is error, how to fix?
![Screenshot 2022-08-22 143019](https://user-images.githubusercontent.com/111732700/185864400-ad8d8796-0e83-4383-99b2-8470c169d328.png)

**Comment by ducquandls** [comment]
duma author @ZitongYu

**Comment by HuangYuKaiLI1031** [comment]
> hello, I run inference is error, how to fix? ![Screenshot 2022-08-22 143019](https://user-images.githubusercontent.com/111732700/185864400-ad8d8796-0e83-4383-99b2-8470c169d328.png)

You can check the input path of the input image and the number of input images
