### ISSUE TITLE
Question about ppg wave

### ISSUE THREAD

**Issue by mok0102** [ZitongYu/PhysFormer#13]
Hello, thank you for provide the PhysFormer code. I have a question about Physformer, so I'm asking 3 questions.

1. How were the frames for each video made?
Currently I'm using ffmpeg to cut video into frames with fps. But I'm wondering if there is another way that you used.

2. About VIPL_fold1_train.txt
I'm wondering why the fps of certain video in VIPL_fold1_train.txt is lower than 25(such as 16). According to the VIPL-HR dataset, it says the fps of videos are 25, 30 but it seems like the fps in VIPL_fold1_train.txt are varying. I wonder how to manipulate raw fps and ppg values.

3. About VIPL_fold1_train.txt 2
I found out that the ppg wave in VIPL-HR is different to VIPL_fold1_train.txt. I'm assuming that some butter bandingpass filter is used, still I want to know how the ppg wave is processed.

**Comment by Z-Xiong** [comment]
same question.
about question 2, I think the camera uses automatic exposure, when the light is not enough, the exposure time becomes longer, resulting in lower true rate. This is also what bothers me about how to handle the dataset.

**Comment by Z-Xiong** [comment]
I think it is possible to downsample the waveform to the real frame rate of the video. This way it can be trained.
